# Generated by Django 4.2.11 on 2024-05-02 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lat",
                    models.FloatField(help_text="latitude", verbose_name="latitude"),
                ),
                (
                    "lng",
                    models.FloatField(help_text="longitude", verbose_name="longitude"),
                ),
                ("imgtime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "filename",
                    models.CharField(
                        help_text="filename", max_length=100, verbose_name="filename"
                    ),
                ),
                (
                    "dirname",
                    models.CharField(
                        help_text="dirname", max_length=100, verbose_name="dirname"
                    ),
                ),
            ],
        ),
    ]
